# wrangler.toml for Cloudflare Pages
name = "eetcg"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
# Remove the pages_build_output_dir as it's handled by @opennextjs/cloudflare

# Environment variables (add as needed)
[vars]
NODE_ENV = "production"
