# wrangler.toml for Cloudflare Pages
name = "eetcg"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/worker"

# Environment variables (add as needed)
[vars]
NODE_ENV = "production"
R2_PUBLIC_URL = "https://pub-d5883a1087a6409384f23475fe808a41.r2.dev" # Update with your actual domain

# R2 bucket binding for OpenNext incremental cache
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "eetcg-next-cache"
preview_bucket_name = "eetcg-next-cache-preview"